config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#index'

  #public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-conditions' => 'pages#terms_conditions'


  resources :employees
  resources :documents

  #example

  # get 'pages/contact_us'
  # get 'pages/privacy_policy'
  # get 'pages/terms_conditions'

  #get 'home/index'   #url /home/index
  #get '/home' => 'home#index' #url /home





end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :documents
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  # validates :city, :state, :country, :phone_number, :address_line_1, :address_line_2, presence: true

  def name
    "#{first_name} #{last_name}".strip
  end
  def name_with_email
   "#{name} - #{email}"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :show, :destroy]

  def index
    begin
      # Initialize Redis
      redis = Redis.new

      # Check if employees are cached in Redis
      if redis.exists("employees")  && redis.exists("employees") != 0
        employees_json = JSON.parse(redis.get("employees"))
        @employees = employees_json.map do |employee|
          Employee.new(
            id: employee['id'],
            first_name: employee['first_name'],
            last_name: employee['last_name'],
            email: employee['email'],
            city: employee['city'],
            state: employee['state'],
            country: employee['country'],
            pincode: employee['pincode'],
            phone_number: employee['phone_number'],
            address_line_1: employee['address_line_1'],
            address_line_2: employee['address_line_2'],
            created_at: Time.parse(employee['created_at']),
            updated_at: Time.parse(employee['updated_at'])
          )
        end
      else
        # Fetch employees from the database
        @employees = Employee.all

        # Store employees in Redis for caching with a TTL of 1 hour
        redis.set("employees", @employees.to_json, ex: 1.hour)
      end
    rescue => e
      # Log the error
      Rails.logger.error "Error in EmployeesController#index: #{e.message}"
      # Render an error page or handle the error as appropriate
      render plain: "An error occurred while processing your request", status: :internal_server_error
    end
  end


  def new
    @employee  = Employee.new
    respond_to do |format|
      format.html # Render HTML normally
      format.js   # Render JavaScript response (for AJAX request)
    end
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      # Clear the employees cache when a new employee is created
      redis.del("employees")
      # redirect_to employees_path, notice: 'Employee has been created'
      respond_to do |format|
        format.html { redirect_to employees_path }
        format.js   # Render JavaScript response (for AJAX request)
      end
    else
      render :new
    end
  end

  def edit

  end

  def show
  end

  def destroy
    if @employee.destroy
      redirect_to employees_path, notice: 'Employee has been deleted'
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Employee has been updated'
    else
      render :edit
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :city, :state, :country, :pincode, :phone_number, :address_line_1, :address_line_2)
  end

  def set_employee
      @employee = Employee.find(params[:id])
    rescue ActiveRecord::RecordNotFound => error
     redirect_to employees_path, notice: "The employee you were looking for could not be found."
  end

  def redis
    @redis ||= Redis.new
  end

end

app/views/employees/_form.html.erb
<%= form_with model: employee do  |form|%>
    <div class="row">
          <% if employee.errors.any? %>
      <div class='col-lg-12'>
       <p class='lead'>Please fix errors blow</p>
       <%# employee.errors.full_messages.each do |message|%>
        <%# <p class='text-danger'><%= message%></p>
       <%#end%>
      </div>
      <%end%>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :first_name, class: 'mb-2'%>
          <%= form.text_field :first_name, class: 'form-control form-control-lg rounded-0'%>
          <% employee.errors.full_messages_for(:first_name).each do |message|%>
            <p class='text-danger'><%= message%></p>
          <%end%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :last_name, class: 'mb-2'%>
          <%= form.text_field :last_name, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :email, class: 'mb-2'%>
          <%= form.text_field :email, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
       <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :city, class: 'mb-2'%>
          <%= form.text_field :city, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :state, class: 'mb-2'%>
          <%= form.text_field :state, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :country, class: 'mb-2'%>
          <%= form.text_field :country, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :pincode, class: 'mb-2'%>
          <%= form.text_field :pincode, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :phone_number, class: 'mb-2'%>
          <%= form.text_field :phone_number, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :address_line_1, class: 'mb-2'%>
          <%= form.text_field :address_line_1, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :address_line_2, class: 'mb-2'%>
          <%= form.text_field :address_line_2, class: 'form-control form-control-lg rounded-0'%>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-lg-12 mt-4'>
        <%= form.submit class: 'btn btn-primary btn-lg rounded-0'%>
        <%= link_to 'Back to Employees', employees_path, class: 'btn btn-outline-primary btn-lg rounded-0'%>
      </div>
    </div>
  <%end%>

app/views/employees/create.js.erb
<!-- app/views/employees/create.js.erb -->

$('#addEmployeeModal').modal('hide');  // Hide the modal
$('#flash-messages').html("<%= j render 'shared/flash_messages' %>"); // Update flash messages

app/views/employees/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">Edit New Employee</h2>
    </div>
  </div>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
  <%= flash[:notice]%>
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">List of employees</h2>
    </div>
  </div>
  <%= link_to "Add New Employee", new_employee_path, class: "btn btn-primary btn-lg mb-4 mt-4 rounded-0" %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>City</th>
        <th>State</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee|%>
        <tr>
          <td><%= employee.name%></td>
          <td><%= employee.email%></td>
          <td><%= employee.phone_number%></td>
          <td><%= employee.city%></td>
          <td><%= employee.state%></td>
          <td>
          <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-primary" %>
          <%= link_to "Show", employee_path(employee), class: "btn btn-primary" %>
          <%= link_to "Delete", employee_path(employee), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure to delete this employee?'} %>
          <%#= link_to "Delete", employee_path(employee), data: { 'method': :delete, 'confirm': "Are you sure?" } %>

          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">Create New Employee</h2>
    </div>
  </div>
  <%=render 'form', employee: @employee %>
  <%#= render partial: 'form', locals: { employee: @employee } %> 
  <%# partial key is used then locals: {ss: @ss} use this way %>
  <%#= render(partial: 'form', locals: { employee: @employee }) %>

</div>

app/views/employees/show.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">Employee Details</h2>
    </div>
  </div>
  <%= link_to "Add New Employee", new_employee_path, class: "btn btn-primary btn-lg mb-4 mt-4 rounded-0" %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>City</th>
        <th>State</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @employee.name%></td>
          <td><%= @employee.email%></td>
          <td><%= @employee.phone_number%></td>
          <td><%= @employee.city%></td>
          <td><%= @employee.state%></td>
          <td>
          <%= link_to "Edit", edit_employee_path(@employee), class: "btn btn-primary" %>
          </td>
        </tr>
    </tbody>
    <%= link_to 'Back to Employees', employees_path, class: 'btn btn-outline-primary btn-lg rounded-0'%>
  </table>
  <%if @employee.documents.present?%>
      <div class='row mt-5'>
  <h2 class='text-center'>Employee Documents</h2>
  <% @employee.documents.each do |document|%>
    <div class='card md-4'>
     <div class='card-body'>
      <div class='row'>
        <div class='col-lg-4'>
          <%if document.image.attached?%>
            <%= image_tag document.image, class: 'img-fluid' %>
          <%end%>
        </div>
        <div class='col-lg-4'>
        <p class='lead'><%= document.name%></p>
        </div>
        <div class='col-lg-4'>
          <p class='lead'><%= document.doc_type%></p>
        </div>
      </div>
     </div>
    </div>
  <%end%>
  </div>
  <%end%>
</div>