config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#index'

  #public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-conditions' => 'pages#terms_conditions'


  resources :employees
  resources :documents

  #example

  # get 'pages/contact_us'
  # get 'pages/privacy_policy'
  # get 'pages/terms_conditions'

  #get 'home/index'   #url /home/index
  #get '/home' => 'home#index' #url /home





end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'HR-Mitra', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <% if user_signed_in?%>
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Settings
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="javascript:void(0)">Signed in as <%= current_user.email%></a></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, class: 'dropdown-item', method: :delete, data: { confirm: "If you sign out , your current session will be destroyed" } %></li>
            </ul>
          </li>
        <%else%>
           <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link active'%>
           </li>
        <%end%>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<h1>HR-Mitra</h1>
<%= link_to 'About Us', about_path, target: '_blank', data: {name: 'about-page'}  %>
<%= link_to 'Contact Us', contact_path, target: '_blank', data: {name: 'about-page'}  %>
<%= link_to 'Privacy Policy', privacy_policy_path, target: '_blank', data: {name: 'about-page'}  %>
<%= link_to 'Terms and Conditions', terms_conditions_path, target: '_blank', data: {name: 'about-page'}  %>


<%#= link_to 'About Us', about_path  %>
<%#= link_to 'About Us', controller: :pages, action: :about_us  %>
<%#= link_to 'About Us', about_url  %>
<%#= link_to 'About Us', '/about'  %>