config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#index'

  #public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-conditions' => 'pages#terms_conditions'


  resources :employees
  resources :documents

  #example

  # get 'pages/contact_us'
  # get 'pages/privacy_policy'
  # get 'pages/terms_conditions'

  #get 'home/index'   #url /home/index
  #get '/home' => 'home#index' #url /home





end

app/models/document.rb
class Document < ApplicationRecord

  DOC_TYPES = ['Marksheet', 'Photo ID', 'Address Proof', 'Others'].freeze
  belongs_to :employee
  has_one_attached :image
  validates :name, :doc_type, :employee_id, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :set_document, only: [:edit, :update, :show, :destroy]

    def index
        @documents = Document.all
    end

    def new
      @document  = Document.new
    end

    def create
      @document = Document.new(document_params)
      if @document.save
        redirect_to documents_path, notice: 'Document has been created'
      else
        render :new
      end
    end

    def edit

    end

    def show
    end

    def destroy
      if @document.destroy
        redirect_to documents_path, notice: 'Document has been deleted'
      end
    end

    def update
      if @document.update(document_params)
        redirect_to documents_path, notice: 'Document has been updated'
      else
        render :edit
      end
    end

    private

    def document_params
      params.require(:document).permit(:name, :doc_type, :employee_id, :image)
    end

    def set_document
        @document = Document.find(params[:id])
      rescue ActiveRecord::RecordNotFound => error
       redirect_to documents_path, notice: "The document you were looking for could not be found."
    end
end

app/views/documents/_form.html.erb
<%= form_with model: document do |form|%>
  <div class='row'>
    <div class='col-lg-4'>
      <div class='form-group'>
        <%= form.label :name, class: 'mb-2'%>
        <%= form.text_field :name, class: 'form-control form-control-lg rounded-0'%>
        <% document.errors.full_messages_for(:name).each do |message|%>
          <p class='text-danger'><%= message%></p>
        <%end%>
      </div>
      <div class='form-group'>
        <%= form.label :doc_type, class: 'mb-2'%>
        <%= form.select :doc_type, options_for_select(Document::DOC_TYPES, selected: document.doc_type), {prompt: 'Select document types'}, class: 'form-select form-select-lg rounded-0' %>
        <% document.errors.full_messages_for(:doc_type).each do |message|%>
          <p class='text-danger'><%= message%></p>
        <%end%>
      </div>
      <div class='form-group'>
        <%= form.label :employee_id, class: 'mb-2'%>
        <%= form.select :employee_id, options_for_select(Employee.all.map{ |emp| [emp.name_with_email, emp.id]}, selected: document.employee_id), {prompt: 'Select employee'}, class: 'form-select form-select-lg rounded-0' %>        
      </div>
      <div class='form-group'>
        <%= form.label :image, class: 'mb-2'%>
        <%= form.file_field :image, class: 'form-control form-control-lg rounded-0' %>        
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-lg-12 mt-4'>
      <%= form.submit class: 'btn btn-primary btn-lg rounded-0'%>
      <%= link_to 'Back to Document', documents_path, class: 'btn btn-outline-primary btn-lg rounded-0'%>
    </div>
  </div>
<%end%>

app/views/documents/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">Edit New Document</h2>
    </div>
  </div>
  <%= render 'form', document: @document %>
</div>

app/views/documents/index.html.erb
<div class="col-lg-12">
  <%= flash[:notice]%>
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">List of Documents</h2>
    </div>
  </div>
  <%= link_to "Add New Document", new_document_path, class: "btn btn-primary btn-lg mb-4 mt-4 rounded-0" %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Document Type</th>
        <th>Employee ID</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @documents.each do |document|%>
        <tr>
          <td><%= link_to document.name, employee_path(document.employee) %></td>
          <td><%= document.doc_type%></td>
          <td><%= document.employee_id%></td>
          <td>
          <%= link_to "Edit", edit_document_path(document), class: "btn btn-primary" %>
          <%= link_to "Show", document_path(document), class: "btn btn-primary" %>
          <%= link_to "Delete", document_path(document), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure to delete this document?'} %>
          <%#= link_to "Delete", employee_path(employee), data: { 'method': :delete, 'confirm': "Are you sure?" } %>

          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/documents/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">Create New Doucment</h2>
    </div>
  </div>
  <%= render 'form', document: @document %>
</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 md-5">
    <div class="card-body">
      <h2 class="text-center">Document Details</h2>
    </div>
  </div>
  <%= link_to "Add New Document", new_document_path, class: "btn btn-primary btn-lg mb-4 mt-4 rounded-0" %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Document Type</th>
        <th>Employee ID</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @document.name%></td>
          <td><%= @document.doc_type%></td>
          <td><%= @document.employee_id%></td>
          <%if @document.image.attached?%>
            <%= image_tag @document.image, class: 'img-fluid' %>
          <%end%>
          <td>
          <%= link_to "Edit", edit_document_path(@document), class: "btn btn-primary" %>
          </td>
        </tr>
    </tbody>
    <%= link_to 'Back to Documents', documents_path, class: 'btn btn-outline-primary btn-lg rounded-0'%>
  </table>
</div>